# Generated by Django 4.1.5 on 2023-01-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="product",
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="stock_app.product"),
        ),
    ]
